# Generated by Django 2.2.1 on 2019-05-19 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0002_makale_makale_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_sahibi', models.CharField(max_length=50, verbose_name='isim')),
                ('yorum_text', models.CharField(max_length=250, verbose_name='yorum')),
                ('yorum_tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='makale.Makale', verbose_name='Makale')),
            ],
        ),
    ]
