# Generated by Django 2.2.1 on 2019-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0005_auto_20190519_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
