# Generated by Django 2.2.1 on 2019-05-25 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0006_makale_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='favori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_post_id', models.IntegerField()),
                ('liked_by', models.IntegerField()),
                ('liked_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.Makale')),
            ],
        ),
    ]
