# Generated by Django 2.2.1 on 2019-05-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0008_auto_20190525_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favori',
            name='makale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.Makale'),
        ),
    ]
