# Generated by Django 2.2.1 on 2019-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0009_auto_20190526_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
