# Generated by Django 2.2.1 on 2019-05-26 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0010_makale_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='icerik',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100), django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='makale',
            name='makale_foto',
            field=models.FileField(upload_to='', verbose_name='Fotoğraf Ekle'),
        ),
    ]
