# Generated by Django 2.2.1 on 2019-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190526_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twitter Kullanıcı Adı'),
        ),
    ]
